# A minimal serverless.yml which shows how to reference resources in CloudFormation stacks managed outside of serverless.yml
service: serverless-cloudformation

custom:
  userPoolArn: ${cf:app-userpool.UserPoolArn}

provider:
  name: aws
  runtime: python3.6
  region: ${env:AWS_REGION} # work around https://github.com/serverless/serverless/issues/3947

functions:
  index:
    handler: handler.index
    timeout: 12
    events:
      - http:
          path: /
          method: get
          authorizer:
           arn: ${self:custom.userPoolArn}
